version: "3"

services:
  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    ports:
      - 8000:8000
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./myapp:/var/www
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mailhog

  php:
    container_name: laravel_php
    build: ./docker/php
    volumes:
      - ./myapp:/var/www
      - ./logs:/var/log/nginx
    environment:
      TZ: "Asia/Tokyo"

  db:
    container_name: laravel_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: b2UcuTPQ
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: laravel-pass
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    container_name: laravel_myadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db

  https-portal:
    container_name: laravel_https_portal
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    environment:
      STAGE: local
      DOMAINS: "localhost -> http://nginx:8000"
    volumes:
      - ./docker/https-portal/certs:/var/lib/https-portal
    links:
      - nginx

  mailhog:
    container_name: laravel_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      TZ: Asia/Tokyo
